### ISSUE TITLE
Add colums

### ISSUE THREAD

**Issue by jreubens** [jreubens/Vecmo-Tagsheet-Converter-to-ETN-format#1]
I want to add extra columns to the dataframe as there are several headers that are not in the Vemco Tagsheet, but are needed for the ETN data import. See #L69 of the script...

What's the best way to add extra columns and give them all the same value/text.
e.g. I want to add the column 'Manufacturer' and for all tags you want to upload it should contain 'Vemco'.

In addition, for some of the new colums, the info it should contain is based on an input from another (already existing column). E.g the new column 'idCode' yields some info stored in the already existing column 'tagCodeSpace'. How to do this split?

@PieterjanVerhelst, @JolienGoossens can you help me on this issue

**Comment by PieterjanVerhelst** [comment]
I'll have a look at it today.

**Comment by JolienGoossens** [comment]
I branched a solution this morning! Add_columns

**Comment by PieterjanVerhelst** [comment]
If you merged the branch with the solution (and Jan confirmed the solution), you can close this issue with a '#' and a link to that branch.

**Comment by JolienGoossens** [comment]
Now it's pull request #2 waiting for confirmation of Jan. Good like this?

**Comment by PieterjanVerhelst** [comment]
What a team :)

**Comment by jreubens** [comment]
I just merged the branch to the master
